url: https://dumati-consultancy-services-ltd.github.io

# Site settings
title: Awesome Title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Ankit
  pic: 1
  position: Managing Director

- name: Su
  pic: 2
  position: HR Director

- name: Sandeep
  pic: 3
  position: Lead Developer
  #social:
   # - title: twitter
    #  url: #
    #- title: facebook
     # url: #
    #- title: google-plus
     # url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket 
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Suite 10,
  - line: 3-5 Wilson Patten Street,
  - line: Warrington, Cheshire.
  - line: WA1 1PG

# Build settings
markdown: kramdown
permalink: pretty
